'use strict';

// tests for get
// Generated by serverless-jest-plugin

const mod = require('./../dist/get');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('get', () => {
  it('retreival of single user', () => {
    const event = {
      httpMethod: 'GET',
      pathParameters: {
        id: 1,
      },
    };
    return wrapped.run(event).then((response) => {
      expect(response).toBeDefined();
    });
  });
});
