'use strict';

// tests for get lambda function
// Generated by serverless-jest-plugin

const mod = require('./../dist/get');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

// Main test suite for the get lambda function
describe('get', () => {
  const event = {
    httpMethod: 'GET',
    pathParameters: {
      id: 1,
    },
  };

  // Ask the lambda function for a user with rowid=1
  // Test succeeds if statusCode=200
  it('fetching specific user', async () => {
    return wrapped.run(event).then((response) => {
      expect(response.statusCode).toBe(200);
    });
  });
});
