'use strict';

// tests for list
// Generated by serverless-jest-plugin

const mod = require('./../dist/list');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('list', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('test fetching all users', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(response.statusCode).toBe(200);
    });
  });
});

describe('list', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('test fetching some users', () => {
    return wrapped.run({}).then((response) => {
      const body = JSON.parse(response.body);
      expect(response.statusCode).toBe(200);
    });
  });
});
